### ISSUE TITLE
Authorization: mount_nfs: Permission denied

### ISSUE THREAD

**Issue by jonryf** [kofemann/simple-nfs#13]
Hey!
I have an issue when I try to mount the simple-nfs server on macOS (locally). When I type the following command:
`sudo mount -t nfs localhost:/ /Users/jon/Desktop/test2/`
It returns the following error message:
`mount_nfs: can't mount / from localhost onto /Users/jon/Desktop/test2: Permission denied`

How can I solve this authorization problem? I have made no modifications to the example code here.

Thanks, Jon

**Comment by kofemann** [comment]
Hi Jon,

this is probably due to security settings. Try to mount with unix standard security:

```
sudo mount -t nfs -o sec=sys localhost:/ /Users/jon/Desktop/test2/
```

The other issue can we with the portmapper. I have updated code to include embedded portmapper. You can start the server as:

```
$ sudo java -jar target/simple-nfs-1.0-SNAPSHOT-jar-with-dependencies.jar -with-portmap
```

Thanks,
  Kofemann.

**Comment by jonryf** [comment]
Hey!
Thanks a lot, solved my issue 👍
