### ISSUE TITLE
no file present on mounted folder

### ISSUE THREAD

**Issue by hassin23ayz** [kofemann/simple-nfs#18]
hello thanks for your library 
i was able to run nfs server under ubuntu here is my exports files 

`/home/ayx/AAA/nfs-Server *(rw,all_squash,sec=sys)`

at the client side i used the following mount command 

`sudo mount.nfs -o nfsvers=4.1,nolock,noacl -rw -v 192.168.0.105:/home/ayx/AAA/nfs-Server nfs-Client`

the folder gets mounted but there are no files present 
what is that i am doing wrong ?

**Comment by kofemann** [comment]
On which OS do you run? Can you enable debug level?

**Comment by hassin23ayz** [comment]
Hello thanks A lot for your reply 

i am running the code on intelliJ , OS is Ubuntu 18.04 , how to enable debug level at your code ? 
this is the picture of my code running 
![Selection_009](https://user-images.githubusercontent.com/5806239/66336586-30b76100-e95f-11e9-9c2c-895859f3227b.png)

**Comment by kofemann** [comment]
You need to start server -root option that points to /home/ayx/AAA/nfs-Server directory

**Comment by hassin23ayz** [comment]
i have tried to run the app using the following command 

`ayx@ayx-ThinkPad:~/projects/SyncOS/simpleNfsServer/out/artifacts/simpleNfsServer_jar$ sudo java -cp simpleNfsServer.jar org.dcache.simplenfs.App -root=/home/ayx/AAA/nfs-Server`

it has created "home/ayx/AAA/nfs-Server" 
```

ayx@ayx-ThinkPad:~/AAA$ tree nfs-Server/
nfs-Server/
├── home
│   └── ayx
│       └── AAA
│           └── nfs-Server
└── test.txt

4 directories, 1 file
```
i am quite sure my command arguments are not correct , how do i put appropriate exports and point to server's shared folder path to the app ? thanks

**Comment by hassin23ayz** [comment]
here is my latest attempt result 

![Selection_011](https://user-images.githubusercontent.com/5806239/66343122-c3aac800-e96c-11e9-8d7e-a1f1a09d7ae4.png)

**Comment by kofemann** [comment]
you should export `/` in the exports file as it relative to `root`. e.g.

```
/home/ayx/AAA/nfs-Server *(rw,all_squash,sec=sys)
```

**Comment by hassin23ayz** [comment]
THANKS A LOT, it has worked , i am putting my setup image so that others can get help if stuck 
![Selection_012](https://user-images.githubusercontent.com/5806239/66356014-404c9f00-e98b-11e9-94c3-4ae174d3f525.png)
