### ISSUE TITLE
SimpleNfsServer does not support relative path exports.

### ISSUE THREAD

**Issue by svenin** [kofemann/simple-nfs#8]
Trying to create a SimpleNfsServer with a an export that is not the root export fails when the export is resolved as an absolute path instead of a relative path inside the root of the LocalFileSystem. Note that exports in ExportFile must start with a '/' or they are not parsed by ExportFile.
I suggest assuming all exports are relative and removing the heading '/' when parsing the exports in LocalFileSystem constructor. See my suggested fix at https://github.com/svenin/simple-nfs.

**Comment by kofemann** [comment]
closed by 5544293d3204a818b13b18c00d8af3d41de4b134
